import type { Metadata } from "next";
import { Geist, Roboto_Mono } from "next/font/google";
import Navbar from "./components/Pages/hf/Navbar";
import Footer from "./components/Pages/hf/Footer";
import "./globals.css";

import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "SafarHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="bottom-right" reverseOrder={false} />
        <main className="bg-sky-50">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
